package e

type ErrorCode uint32

const (
	SUCCESS        ErrorCode = 200
	ERROR          ErrorCode = 500
	INVALID_PARAMS ErrorCode = 10001
)

const (
	ERR_AUTH_CHECK_TOKEN_FAIL ErrorCode = iota + 10100
	ERR_AUTH_CHECK_TOKEN_TIMEOUT
	ERR_AUTH_TOKEN_NOTFOUND
	ERR_AUTH_TOKEN_NOTCREATE

	ERR_PASSWORD_CRYPT_FAIL
	ERR_PASSWORD_ERROR

	ERR_PARAMS_EMPTY_MOBILE
	ERR_PARAMS_EMPTY_PASSWORD
	ERR_PARAMS_MOBILE_INVALID
	ERR_PARAMS_USERNAME_EXIST
	ERR_PARAMS_USERNAME_NOTEXIST
	ERR_PARAMS_PASSWORD_INVALID

	ERR_USERNAME_NOT_ACTIVATED
	ERR_USERNAME_LOCKED

	ERR_UPLOAD_FILE_NOTFOUND
	ERR_UPLOAD_FILE_ERROR
	ERR_UPLOAD_FILE_QINIU_FAIL

	ERR_PARAMS_COMPANY_EMPTY_NAME
	ERR_PARAMS_COMPANY_EMPTY_CONTACT_NAME
	ERR_PARAMS_COMPANY_EMPTY_CONTACT_MOBILE
	ERR_PARAMS_COMPANY_EMPTY_ADDRESS
	ERR_PARAMS_COMPANY_EMPTY_ADDRESS_POST
	ERR_PARAMS_COMPANY_EMPTY_LICENSE_PIC
	ERR_COMPANY_NAME_EXIST
	ERR_COMPANY_CONTACT_MOBILE_ERROR
	ERR_COMPANY_ADDRESS_POST_ERROR
	ERR_COMPANY_LICENSE_PIC_ERROR
	ERR_COMPANY_CREATE_FAIL
	ERR_COMPANY_GET_FAIL
	ERR_COMPANY_VERIFY_FAIL
	ERR_PARAMS_COMPANY_VERIFY_EMPTY_COMPANY_ID
	ERR_PARAMS_COMPANY_VERIFY_STATUS_ERROR
)
